### ISSUE TITLE
Adds duplicate wallpapers to background picker

### ISSUE THREAD

**Issue by lukors** [JeysonFlores/switcher#6] opened 2021-12-15 11:06 UTC
After using Switcher I get duplicated wallpapers showing up in my background picker.

![image](https://user-images.githubusercontent.com/1719884/146175358-125bc0e8-e6ee-49e1-86ba-7b94cc971e29.png)

I have not investigated when they show up. They don't seem to show up right away, but after a while, perhaps after a reboot, they seem to pop up.

**Comment by JeysonFlores** [comment] 2021-12-15 23:42
Switcher doesn't interact with the Desktop Plug directly. It uses the default Pantheon's contractor to set wallpapers, switcher doesn't allocate wallpapers directly neither reads or writes data that could lead to a misbehavior of the Desktop Plug. 
According to the [Desktop Plug](https://github.com/elementary/switchboard-plug-pantheon-shell) it reads the data from the `~/.local/share/backgrounds` folder, then lists all the files stored there and finally loads them up. If you see the same images in the plug it's because (for some reason) there are duplicates of the same image but with different names.

**Comment by JeysonFlores** [comment] 2021-12-15 23:45
If switcher is the reason they appear it's not the code on this repository the one who creates duplicates of the wallpapers, it's the contractor. Which is used not only by switcher but is used by other apps as well like [Fondo](https://github.com/calo001/fondo/).

**Comment by lukors** [comment] 2021-12-15 23:53
I guess the difference between Fondo and this app is that Fondo is only interested in third party wallpapers. Since Switcher can very well be used with default first party wallpapers, it should probably do something differently so duplicates don't appear when you do.

**Comment by lukors** [comment] 2021-12-15 23:57
It would probably be neater to steal most of the wallpaper picker from the desktop plug to get all the same functionality. This would also result in the same wallpapers being displayed in the desktop plug and Switcher, which sounds desirable to me.

**Comment by JeysonFlores** [comment] 2021-12-16 00:16
Can you look at your` ~/.local/share/backgrounds` and see what's there? If there's a duplicate of the wallpaper it means they have different names.

**Comment by lukors** [comment] 2021-12-16 00:28
Yep, they are both there, but they have the same name.

So identical backgrounds are located in both `/usr/share/backgrounds/` and `~/.local/share/backgrounds/`. And they both show up in my background picker.

I'm curious on how they end up in my `~/.local/share/backgrounds/` because they don't appear there when I pick a wallpaper in Switcher or when the theme changes. I had a feeling they appeared on reboot or wake from sleep, which seems odd.

Needs more investigation.

**Comment by JeysonFlores** [comment] 2021-12-16 20:16
About this. I've never had this problem. I've been using Switcher since the first mockups and there's never been duplicated wallpapers on my wallpaper picker section. Something odder is the fact that` /usr/share/backgrounds/` is a protected directory, and Switcher has no permissions for interacting with that directory, see the [flatpak manifest](https://github.com/JeysonFlores/switcher/blob/main/com.github.jeysonflores.switcher.yml).

**Comment by JeysonFlores** [comment] 2021-12-16 20:17
I've also read the code of the Desktop Plug and there's nothing that could lead to this problem. It seems that anything that is causing this, it's foreign to switcher (or the desktop plug).

**Comment by JeysonFlores** [comment] 2021-12-17 03:42
I'll close this. If in the future there's more information about this I'll reopen it again.

**Closed as completed** 2021-12-17 03:42 UTC
Labels: odd
